# Generated by Django 5.2.12 on 2026-03-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options_group_created_by_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('casa', 'Casa'), ('viagem', 'Viagem'), ('casal', 'Casal'), ('trabalho', 'Trabalho'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria'),
        ),
    ]
